aivaultReplicaCount: 1
aivaultEntityReplicaCount: 1
namespace: ai-vault-ns

aivaultImage:
  repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/ethical-web-ai/ai-vault-app:0.3.0
  pullPolicy: Always
  tag: ""

aivaultEntityImage:
  repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/ethical-web-ai/ai-vault-entity:0.1.0
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8000

resources: {}

env:
  gpcBaseUrl: "aivault.myorg.tld"
  gptDataDbUser: "yourdbuser"
  gptDataDbHost: "yourdbhost"
  gptDataDbName: "ai_vault"
  nlpApiUrl: "http://ai-vault-entity-svc/entities"
  mailFrom: "support@bubblr.com"
  mailServer: "smtp.office.365.com"
  mailServerPort: "587"
  initialUser: "support@bubblr.com"
  smtpLoginId: "support@bubblr.com"
  aiSeekEnterPriseService: "https://aiseek-enterprise.production.prodsvc.com"

ingress:
  host: aivault.ai-vault.io
  className: "alb"
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /v1/client/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/subnets: 	subnet-123456789,subnet-473857823784,subnet-68794513435  #Replace this with your own public subnets
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:245758476846852:certificate/35fg6w54e5b6e-645b-4442-b456-72c571240d7f #Replace this with your ACM certifcate ARN
    alb.ingress.kubernetes.io/group.name: ai-vault
    alb.ingress.kubernetes.io/load-balancer-name: ai-vault

