aivaultReplicaCount: 1
aivaultEntityReplicaCount: 1
namespace: ai-vault-ns

aivaultImage:
  repository: 475755457693.dkr.ecr.eu-west-2.amazonaws.com/ai-vault/production
  pullPolicy: Always
  tag: ""

aivaultEntityImage:
  repository: 475755457693.dkr.ecr.eu-west-2.amazonaws.com/ai-vault-entity/production
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources: {}

env:
  awsS3BucketHtml: ""
  awsS3BucketHtmlCDN: ""
  htmlPageAwsS3Bucket: ""
  htmlPageCDN: ""
  gpcBaseUrl: ""
  gptDataDbUser: ""
