---
apiVersion: v1
kind: Service
metadata:
  name: ai-vault-entity-svc
  labels:
    application: ai-vault-entity-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.service.port }}
      name: ai-vault-entity
  selector:
    app: ai-vault-entity
  type: {{ .Values.service.type }}
